### PR TITLE
Gj refactor player

### PR DESCRIPTION
**Pull request by grace-joh**
## Describe your changes
- added type and symbol to Player instantiation
- remove type as instance variable
  - because we decided we didn't need it!
- update tests for Player #initialize

## Checklist before requesting a review
- [x] I have performed a self-review of my code.
- [x] I have added/updated corresponding tests.

### CODE REVIEW

**Comment by grace-joh** [comment]
Sorry to be confusing with the type instance variable! 
Thank you for messaging to clarify what we wanted!

**Review by margdaly — COMMENTED** [review]
So glad we got to use inheritance!

**Review by margdaly — APPROVED** [review]
We'll have to make sure all spec_test get updated with the new Player and Computer initialization and I'm so glad I know how to actually use command d now!

**Comment by grace-joh** [comment]
Yes! I'll make a new card on our Project Board called Refactor for everything we change. That way, we can keep track of what to review/make sure we updated in terms of each change!

**Pull request merged**
